### ISSUE TITLE
Implement to_py_error as a From trait  for PyErr and VirtualMachineError

### ISSUE THREAD

**Issue by pefontana** [lambdaclass/cairo-rs-py#180]
To reduce some boilerplate code, rewrite the `fn to_py_error` as a From trait for `PyErr` and `VirtualMachineError`.
Then we should replace all the  `.map_err(to_py_error)` with `.into()`.

**Comment by AminArria** [comment]
So there is an issue with this idea, it would require us to break Rust's orphan rules and the solution of using a wrapper class would end up complicating things more instead simplifying

An example `impl` 

```rust
impl From<Result<CairoRunner, RunnerError>> for Result<(), PyErr> {
    fn from(_: Result<CairoRunner, RunnerError>) -> Self {...}
}
```

In this case all things are external `Result`, `CairoRunner`, `RunnerError`, and `Pyerr` which causes the orphan rule violation

More context on orphan rule and solution involving wrapper type [Using the Newtype Pattern to Implement External Traits on External Types](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-the-newtype-pattern-to-implement-external-traits-on-external-types)
